version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: "sunday"
      time: "11:00" # 11am UTC
    reviewers:
      - "adrianbrad"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "adrianbrad"

  - package-ecosystem: docker
    directory: "/d8t"
    schedule:
      interval: weekly
    reviewers:
      - "adrianbrad"