name: Vulnerability scanner

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: 1.19

jobs:
  vulns:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go list
        run: go list -json -deps > go.list

      - name: nancy
        uses: sonatype-nexus-community/nancy-github-action@v1.0.2